services:
  - type: web
    name: adugalam-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn adugalam_api.wsgi"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: adugalam-db
          property: connectionString

databases:
  - name: adugalam-db
    databaseName: adugalam
    user: adu_admin
